### ISSUE TITLE
Defining Entry Model Error

### ISSUE THREAD

**Issue by neifreitas** [ehmatthes/pcc_2e#10]
Hi Eric! 
I hope you and your family are well!

I tried to execute makemigrations for Entry model described on page 518 (Second Edition) and Django return an error: 

TypeError: __init__() missing 1 required positional argument: 'on_delete'

I discoverd on Stackoverflow that  since Django 2.0 the ForeignKey field requires two positional arguments and I made the modification below, after this makemigrations works fine!

`topic = models.ForeignKey(Topic, on_delete=models.CASCADE)`

Best Regards!
Nei Freitas

**Comment by ehmatthes** [comment]
Hi Nei. I believe you are using the first edition of the book. Updates for chapter 18 of the first edition are here: <http://ehmatthes.github.io/pcc/chapter_18/README.html#updates>.

I added the section about `on_delete` in December of 2017.

**Comment by neifreitas** [comment]
Tks for the information Eric and excuse-me for the incovenience!!
