### ISSUE TITLE
self.text is unscriptable

### ISSUE THREAD

**Issue by Wambug** [ehmatthes/pcc_2e#11]
from django.db import models
# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    texts = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.texts

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField
    date_added =models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return f"{self.text[:50]}..."

**Comment by ehmatthes** [comment]
You never asked a question or described what's happening, but I notice this line:

    text = models.TextField

You are missing the parentheses. This means text is just a reference to the TextField model field, it doesn't actually create a column in the database for your text.

See here: <https://github.com/ehmatthes/pcc_2e/blob/master/chapter_18/starting_an_app/learning_logs/models.py#L15>
