### ISSUE TITLE
self.text is unscriptable

### ISSUE THREAD

**Issue by Wambug** [ehmatthes/pcc_2e#12]
![Screenshot at 2020-06-24 10-56-38](https://user-images.githubusercontent.com/54021365/85519233-b31ca980-b5f0-11ea-9552-2bdf886d9f8d.png)
![Screenshot at 2020-06-24 10-57-52](https://user-images.githubusercontent.com/54021365/85519248-b9128a80-b5f0-11ea-9de6-4a370bca1839.png)

**Comment by ehmatthes** [comment]
When you added the parentheses, you need to migrate the database again:

    $ python manage.py makemigrations learning_logs
    $ python manage.py migrate
