### ISSUE TITLE
The view users.views.register didn't return an HttpResponse object

### ISSUE THREAD

**Issue by Wambug** [ehmatthes/pcc_2e#13]
![Screenshot at 2020-06-29 20-41-52](https://user-images.githubusercontent.com/54021365/86038192-12831b00-ba30-11ea-90f2-3d5eb210da2d.png)
![Screenshot at 2020-06-29 19-34-16](https://user-images.githubusercontent.com/54021365/86032425-dc8d6900-ba26-11ea-98e3-eafff93dd078.png)

**Comment by ehmatthes** [comment]
You have posted a screenshot, with no information about your code and no question. Even though your question is implied, it's still a really good habit to communicate cleary when you have a question in the technical realm. Many people will simply ignore you if you don't share enough information to let people help you easily.

To sort this out, we'd need to see your views.py file to start with. You can post your project in a GitHub repository and link to it, or since it's a short file you can paste it into a comment here (with proper code formatting).

**Comment by Wambug** [comment]
> You have posted a screenshot, with no information about your code and no question. Even though your question is implied, it's still a really good habit to communicate cleary when you have a question in the technical realm. Many people will simply ignore you if you don't share enough information to let people help you easily.
> 
> To sort this out, we'd need to see your views.py file to start with. You can post your project in a GitHub repository and link to it, or since it's a short file you can paste it into a comment here (with proper code formatting).

![Screenshot at 2020-06-29 20-41-52](https://user-images.githubusercontent.com/54021365/86038289-38a8bb00-ba30-11ea-8d03-a42928e42f5b.png)

**Comment by Wambug** [comment]
whenever i try to register a user it's bringing in errors sorry about not explaining my error but thanks for communicating

**Comment by ehmatthes** [comment]
That's helpful. The last few lines are indented under the else block. So a submitted form would render a response, but a blank form would not be rendered.

Those last few lines should be aligned with the if and else block, so they always run after either if or else block runs. See here: <https://github.com/ehmatthes/pcc_2e/blob/master/chapter_19/setting_up_user_accounts/users/views.py#L22>

**Comment by Wambug** [comment]
![Screenshot at 2020-06-29 22-48-59](https://user-images.githubusercontent.com/54021365/86049616-f9836580-ba41-11ea-8336-4fe3029ef4a6.png)
![Screenshot at 2020-06-29 22-49-39](https://user-images.githubusercontent.com/54021365/86049621-fe481980-ba41-11ea-9d9a-112207cd7284.png)

**Comment by Wambug** [comment]
when i go to my homepage and try to click the topic page and i have not registered instead of taking back to my login page it's giving me an error

**Comment by ehmatthes** [comment]
I can not help you with a vague description like that, and no code. You need a way to share your project; either post the project on GitHub and share a link, or you're welcome to email if that's easier. I am ehmatthes at gmail, and if you email please make a zip of your entire project, *except* the `ll_env` directory.

**Comment by Wambug** [comment]
here's my code

**Comment by ehmatthes** [comment]
There's no link in your comment.
