### ISSUE TITLE
User login does not show username password boxes to enter in credentials

### ISSUE THREAD

**Issue by Tanker21** [ehmatthes/pcc_2e#22]
I'm not sure what I may be missing, I'm on page 424 on second edition and have my urls.py (both root and users), login.html, and base.html files all modified/created as in the book and this repo, but when I refresh the web page and click on the login link, I see the login button only, with no text boxes for username or password, so you cannot enter in credentials.  Am I missing something here? 

Python version 3.8.6
Django version 3.1.2

**Comment by ehmatthes** [comment]
You have `{{ forms.as_p }}`, where it should be `{{ form.as_p }}`.

Templates run in a different environment than .py files. If you had a misspelling like that in a .py file, you'd get a `NameError` because forms isn't defined. Or maybe forms would be defined if you'd imported a module named forms, but it wouldn't have an `as_p` attribute, so you'd get an error about that.

In a template if a variable doesn't exist, that element just doesn't get rendered in the page. This silent failing is fairly common in web apps, I believe because missing data is a fairly common issue in web apps, and we'd usually rather fail silently than make the page crash or something.

**Comment by Tanker21** [comment]
I've removed the s from form, saved, restarted the app, but still I only see the submit button, and still no username or password boxes.  
![login_issue](https://user-images.githubusercontent.com/20226900/97756994-80644f80-1ac1-11eb-9438-8dd0037e9bcb.PNG)

I looked around in the Django files and in the env/django/contrib/auth directory I can see the urls.py and views.py files, and the template/registration folders, but in that folder I do not see any html files (I was thinking there would be the template files to render that login page).

So, even after updating that login.html file, I'm still seeing the same issue.

**Comment by ehmatthes** [comment]
Can you post your views.py file from the users app? You can copy and paste the code into a comment, with three backticks before the code and three after.

**Comment by Tanker21** [comment]
The views.py file in the users folder has not yet been modified, so it only has 

"from django.shortcuts import render" 

and no other code.  I am at the point in chapter 19 of setting up user accounts, and the login page, but before creating a log out page and registration of new users.  

My thinking on the workflow was that a click on 'Login' went to the users urls.py, which called the django.contrib.auth.urls file, which called its own view (LogInView class), which then called its own template html file, but I cannot find that html file.

**Comment by ehmatthes** [comment]
I'm at a loss for troubleshooting without seeing all of your code. It sure looks like your template is not receiving the form, but all the issues I can think of that would cause that to happen would keep the page from rendering at all.

Can you share your whole project? You can push it to a GitHub repository, or you can email me. If you email me, make a zip file of everything in your project except the ll_env directory. If you include that, it will probably be too large to make a zip file. I'm ehmatthes at gmail.

**Comment by Tanker21** [comment]
I emailed you the project from my side.

**Comment by ehmatthes** [comment]
Resolved over email. For anyone who comes across this, forms.as_p had been changed in login.html.txt but not in login.html.
