### ISSUE TITLE
Alien Invasion game - _create_alien() method simplification

### ISSUE THREAD

**Issue by luke9g** [ehmatthes/pcc_2e#23]
Hi 👋 

### Chapter 13 "Aliens", "Building the Alien Fleet" section and the following sections

https://github.com/ehmatthes/pcc_2e/blob/078318e4c5a56959586a14dc03e988e9491d4cec/chapter_13/building_alien_fleet/alien_invasion.py#L102-L109

I think the following line:
`alien.rect.y = alien.rect.height + 2 * alien.rect.height * row_number`
could be simplified into:
`alien.rect.y = alien_height + 2 * alien_height * row_number`
because we already have declared `alien_height` variable a few lines earlier (and it's not used):
`alien_width, alien_height = alien.rect.size`

**Comment by ehmatthes** [comment]
You are absolutely correct.

In the first edition I had `alien_width = alien.rect.width`. In the second edition I changed that to `alien_width, alien_height = alien.rect.size`. I think I was intending to do what you just pointed out, but I forgot to change line 108. Thanks for pointing this out, I will try to get this updated in the next printing.
