### ISSUE TITLE
Issues while working with Hackernews API

### ISSUE THREAD

**Issue by Noonet1** [ehmatthes/pcc_2e#24]
Hi, 

First of all I love this book, this is my first time learning to program in any language and I'm having so much fun. 

I am currently working on API's and got to the final assignment, while working on the hackernews API I ran into two issues. 

The first had a pretty clear cause; while calling for the topstories and listing them I got a KeyError for 'descendants'-key. This was caused by items of the type 'job' ([example](https://hacker-news.firebaseio.com/v0/item/25230351.json)), which doesn't have that key. I was able to overcome this issue by putting in a try-except statement. 

For the second issue I got I was not able to find an answer so far; when the items are printed my titles are returned as tuples. The raw data doesn't have any brackets nor did I add them anywhere. 

**final code:**
```
from operator import itemgetter

import requests

# Make an API call and store the response.
url = 'https://hacker-news.firebaseio.com/v0/topstories.json'
r = requests.get(url)
print(f"Status Code: {r.status_code}")

# Process information about each submission.
submission_ids = r.json()
submission_dicts = []
for submission_id in submission_ids[:10]:
    # Make a separate API call for each submission.
    url = f'https://hacker-news.firebaseio.com/v0/item/{submission_id}.json'
    r = requests.get(url)
    print(f"id: {submission_id}\tStatus Code: {r.status_code}")
    response_dict = r.json()

    # Build a dictionary for each article.
    submission_dict = {}
    submission_dict['title'] = response_dict['title'],
    submission_dict['hn_link'] = f"http://news.ycombinator.com/item?id={submission_id}"
    try:
        submission_dict['comments'] = response_dict['descendants']
    except KeyError:
        submission_dict['comments'] = 0

    submission_dicts.append(submission_dict)

submission_dicts = sorted(submission_dicts, key=itemgetter('comments'),
                            reverse=True)

for submission_dict in submission_dicts:
    print(f"\nTitle: {submission_dict['title']}")
    print(f"Discussion link: {submission_dict['hn_link']}")
    print(f"Comments: {submission_dict['comments']}")
```

**example output:**
```
Title: ('How to Think for Yourself',)
Discussion link: http://news.ycombinator.com/item?id=25227651
Comments: 612
```

The only thing I've changed compared to the code in the book is the way the submission_dict is constructed. This was to make it more readable with the try-except statement. 

Hope someone can help me clarify the cause of this issue, thanks in advance!

**Comment by jaybonk** [comment]
The issue is when you are loading the submission_dict.  You have a comma after the assignment statement – which Python is interrupting as you want the element for the submission_dict[‘title’] to stored as a tuple rather than a string.



submission_dict['title'] = response_dict['title'],

**Comment by Noonet1** [comment]
Thanks, totally missed that!

**Comment by Amber202301** [comment]
I got the same issue as your first issue, and your answer solved my issue. Thanks!

**Comment by julietmills** [comment]
You have answered my question! Thanks!
