### ISSUE TITLE
Regarding Documentation

### ISSUE THREAD

**Issue by servesh-chaturvedi** [ehmatthes/pcc_2e#27]
Hey Eric, Thanks for such an awesome and worthwhile resource. I was hoping if you could add information that the image size (in pixels) of the alien ship should be taken care of beforehand. Could be confusing for many beginners like me. Thanks again and best wishes!

**Comment by ehmatthes** [comment]
Hi. I appreciate the suggestion, but I don't think I will add any more information about this. This is the first time anyone has brought this to my attention in years, so I think most people are able to figure it out on their own if an issue arises.

I assume you are talking about the situation where someone downloads a larger image file, which then takes up too much space on the screen? The three solutions I'm aware of are to download a smaller image file, or resize the image file in an image editing tool, or use the transform function in Pygame. I think people find these solutions well enough on their own.
