### ISSUE TITLE
How do I stop the ship from moving off the bottom of the screen?

### ISSUE THREAD

**Issue by NateRY** [ehmatthes/pcc_2e#28]
import pygame

class Shiptot:
	"""A class for the testing_my_skills game program."""

	def __init__(self, ai_game):
		"""Initalize the settings for the player controled ship."""
		self.screen = ai_game.screen
		self.settings = ai_game.settings
		self.screen_rect = ai_game.screen.get_rect()

		# Load ShipTwo image and get its rect.
		self.image = pygame.image.load('images/ship_two.bmp')
		self.rect = self.image.get_rect()
		

		# Start in the midddle of the screen.
		self.rect.center = self.screen_rect.center

		# store the ships position.
		self.x = float(self.rect.x)
		self.y = float(self.rect.y)

		# Movement flag
		self.moving_right = False
		self.moving_left = False
		self.moving_up = False
		self.moving_down = False

	def update(self):
		"""Update the ships position based on the movement of the flag."""
		# Update ships x value not it rect value.
		if self.moving_right and self.rect.right < self.screen_rect.right:
			self.x += self.settings.shiptot_speed
		if self.moving_left and self.rect.left > 0:
			self.x -= self.settings.shiptot_speed

		# Update ships y value not its rect value.
		if self.moving_up and self.rect.top > self.screen_rect.top:
			self.y -= self.settings.shiptot_speed
		if self.moving_down and self.rect.bottom > 0:
			self.y += self.settings.shiptot_speed

		

		# Update rect objects x and y value
		self.rect.x = self.x
		self.rect.y = self.y
		

	def blitme(self):
		"""draw the ship in the current locations."""
		self.screen.blit(self.image, self.rect)

**Comment by NateRY** [comment]
I am trying to complete question 12.4 **Rocket**, in the "**Try It Yourself**" portion of the book (_Python Crash Course: A Hands-on, Project-Based Introduction to Programing_).

**Comment by ehmatthes** [comment]
Here are the [solutions for chapter 12](https://ehmatthes.github.io/pcc_2e/solutions/chapter_12/).
