### ISSUE TITLE
Typo infinite skills

### ISSUE THREAD

**Issue by johnkershaw** [ehmatthes/pcc_2e#39]
In the LeanPub version of the Python Cheat sheet (all) the infinite skills sidebar has an extra 4th sentence which contains the text "mall sprograms".

![IMG_20211110_092017](https://user-images.githubusercontent.com/5265410/141087260-ed99b480-90ed-4856-b5b6-0605a6519cf9.jpg)

**Comment by ehmatthes** [comment]
Fixed in 3e version coming out soon, sorry for the long delay. :/
