### ISSUE TITLE
Usages of self.rect.x in chapter 12

### ISSUE THREAD

**Issue by girolamodaschio** [ehmatthes/pcc_2e#41]
Hi Eric,

I'm building the game with MacOS.

In `ship.py`, page 242, chapter 12 is stated to:
```
# Update rect object from self.x. self.rect.x = self.x
self.rect.x = self.x
```
Although if I do write this in my codebase, I'm not able to move the ship.
I've already checked for relevant [updates](https://ehmatthes.github.io/pcc_2e/updates/second_printing/#chapter-12) but the issue is not solved by using the summoned pygame version.

Thanks!

**Comment by ehmatthes** [comment]
Hi, my guess would be that you are still basing the ship's position off of `self.rect.x`, rather than `self.x`. Your code should look like [this](https://github.com/ehmatthes/pcc_2e/blob/master/chapter_12/piloting_the_ship/ship.py#L26).

If that doesn't help, please share your entire ship.py file.

**Comment by girolamodaschio** [comment]
Sorry for the late reply, and thank you very much. It works!
