### ISSUE TITLE
Chapter 11 Testing a function

### ISSUE THREAD

**Issue by yunwei-cao** [ehmatthes/pcc_2e#45]
Hi Eric,

I came across an error when running the test_name_function.py. While I've figured it out, I feel it would be good to tell you this in case for the updating of the book. Btw, I'm a fresh learner on Python and I really like your book! 

Here is the case:

```
import unittest
from name_function import get_formatted_name

class NameTestCase(unittest.TestCase):
    """Tests for 'name_function.py'."""

    def test_first_last_name(self):
        """Do names like 'Janis Joplin' work?"""
        formatted_name = get_formatted_name('janis', 'joplin')
        self.assertEqual(formatted_name, 'Janis Joplin')

if __name__ == '__main__':
    unittest.main()
```
The traceback shows that there is an error like this:

> AttributeError: module '__main__' has no attribute

So I googled it and I got the solution from the [Medium](https://medium.com/@vladbezden/using-python-unittest-in-ipython-or-jupyter-732448724e31) and the [StackOverflow](https://stackoverflow.com/questions/49952317/python3-for-unit-test-attributeerror-module-main-has-no-attribute-kerne)

```
import unittest
from name_function import get_formatted_name

class NameTestCase(unittest.TestCase):
    """Tests for 'name_function.py'."""

    def test_first_last_name(self):
        """Do names like 'Janis Joplin' work?"""
        formatted_name = get_formatted_name('janis', 'joplin')
        self.assertEqual(formatted_name, 'Janis Joplin')

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)
```
Thank you!

**Comment by ehmatthes** [comment]
Thank you for sharing this. I'm going to close this because this question hasn't come up often enough to warrant an update. (I think it's been asked once or twice in the last ~three years.)

This will stay visible though, so if the question starts to come up more often, it's still noted.
