### ISSUE TITLE
Chapter 15: die.visual.py Issue with Plotly Version

### ISSUE THREAD

**Issue by mrclickboi** [ehmatthes/pcc_2e#46]
Hello all,

There's an issue with the written code that causes it to not work with the newest plotly version. It took me a couple hours to find an explanation, but it seems like the best thing is to just downgrade plotly. Here's a link to a page with a more thorough description. 

https://www.reddit.com/r/learnpython/comments/10cnbrd/pcc_2nd_edition_plotly_unicodeencodeerror/

If you're using windows and the command prompt terminal, the code to downgrade plotly to the cited version is: 

`python -m pip install --user plotly==5.1.0`

Best to you all,

**Comment by ehmatthes** [comment]
The issue was with Plotly, not with the code in the book. That issue was [fixed today](https://github.com/plotly/plotly.py/releases/tag/v5.13.0) in the 5.13.0 release. If you've downgraded Plotly, you can reinstall the latest version, and everything should work.

**Comment by mrclickboi** [comment]
Hello,

This is excellent! Thank you so much for the update and for the excellent book! 

Best,
