### ISSUE TITLE
chapter20->styling_learning_log->templates->learning_logs->base.html: logout error:405

### ISSUE THREAD

**Issue by MUHAMMAD-NIYAS-P** [ehmatthes/pcc_2e#48]
So happy that i completed PCC 2E , great journey, learned a lot, just found this error while trying to logout on chapter20, b/c we are making a get request to users/logout which is invalid one , can be solved with a form and change method to post.. happy to raise a merge request on your replay...

**Comment by ehmatthes** [comment]
Hi, thank you for reaching out. The third edition of Python Crash Course has been out for a year now, so I am no longer updating the second edition. It will become increasingly out of date from this point forward.

The version of this project in the third edition [implements](https://github.com/ehmatthes/pcc_3e/blob/main/chapter_19/setting_up_user_accounts/learning_logs/templates/learning_logs/base.html#L16) a POST-based logout.
