### ISSUE TITLE
Securing Heroku with ENV variables: don't use quotes for string

### ISSUE THREAD

**Issue by teebu** [ehmatthes/pcc_2e#6]
In the book this is wrong when settings the DEBUG string. 

note: _Issue for Windows users._

`heroku config:set DEBUG='FALSE'`

Example:
```
heroku config:set DEBUG=FALSE
heroku config:set DEBUGQUOTES='FALSE'
```

![image](https://user-images.githubusercontent.com/5531844/72657301-85ec1100-3957-11ea-8e3a-c497d349dc14.png)

https://devcenter.heroku.com/articles/config-vars#using-the-heroku-cli

**Comment by ehmatthes** [comment]
Hi, I don't have access to a Windows machine at the moment. Did you get an error, or did it end up including the quotes in the string?

**Comment by teebu** [comment]
There is no error, it just sets the string to whatever you pass, it takes the single quotes as literal value, the proper way is to set it without them.

**Comment by ehmatthes** [comment]
Thank you for this, I addressed it in the latest printing.
