### ISSUE TITLE
User can fire bullet while game is inactive

### ISSUE THREAD

**Issue by bigmekben** [ehmatthes/pcc_2e#7]
While the game is displaying the Play button, the user can create a bullet by pressing the spacebar, even before clicking on the Play button.
You can reproduce this bug by cloning https://github.com/ehmatthes/pcc_2e.git, switching to the \chapter_14\scoring folder, then running the game from there.

**Comment by ehmatthes** [comment]
I appreciate you bringing this to my attention. But it's a really minor issue; the bullet sits stationary inside the top of the ship, and disappears as soon as the player clicks the play button. So I'm not going to address this; it's also a fairly straightforward issue for anyone to fix. Adding a check for `game_active` in the if block in `fire_bullet()` would be a simple way to address this issue.
