### ISSUE TITLE
ValueError, need assistance

### ISSUE THREAD

**Issue by soundpeck** [ehmatthes/pcc_2e#9]
I am receiving a ValueError when I click the "Add Entry" button after adding an entry to a topic.  Below is the information that is coming back regarding the error.

I am a beginner but I believe that this has something to do with line 53 in views.py which reads:

return redirect(request, 'learning_logs:topic', topic_id='topic_id')

For some reason I don't think it likes the "topic_id=topic_id" portion of the arguments.

I have retyped everything and copied code from the repositories to ensure that I have entered everything correctly.

Any help would be appreciated.

-Ben

Request Method: | POST
-- | --
http://127.0.0.1:8000/new_entry/1/
3.0.4
ValueError
Don't mix *args and **kwargs in call to reverse()!
/Users/Ben/Desktop/learning_log/ll_env/lib/python3.8/site-packages/django/urls/resolvers.py in _reverse_with_prefix, line 614
/Users/Ben/Desktop/learning_log/ll_env/bin/python
3.8.2
['/Users/Ben/Desktop/learning_log',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8',  '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',  '/Users/Ben/Desktop/learning_log/ll_env/lib/python3.8/site-packages']
Mon, 30 Mar 2020 17:27:23 +0000

**Comment by soundpeck** [comment]
PS....my files can be seen here..in case you need them: https://github.com/soundpeck/learning_log.git

**Comment by ehmatthes** [comment]
Sorry, I just saw this. I should be able to help you later today.

**Comment by ehmatthes** [comment]
@soundpeck, that link doesn't work for me. When I go to your user page, it says you have 0 repositories. Did you make this repository private? If so, you can either make it public, or add me as a contributor. If you have a free account, you can add up to three contributors to a private repo. To do that, click on Settings on the far right of the repository page, click Manage Access on the left sidebar, and click Invite a Collaborator.

**Comment by ehmatthes** [comment]
I am closing this because it's an individual error and not a problem with the code in the book, but feel free to add a comment and I will continue to help you.
